version: '2.2'
services:

    mongo:
        extends:
          file: local.yml
          service: mongo
        restart: always
        image: mongo:3.6
        container_name: mongo
        expose:
            - 27017
        healthcheck:
            test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5

    redis:
        extends:
          file: local.yml
          service: redis
        restart: always
        image: redis:5.0.0
        container_name: redis
        expose:
            - 6379

    sharelatex:
        extends:
          file: local.yml
          service: sharelatex
        restart: always
        image: sharelatex/sharelatex
        # image: quay.io/sharelatex/sharelatex-pro
        container_name: sharelatex
        depends_on:
            mongo:
                condition: service_healthy
            redis:
                condition: service_started
        ports:
            - 80:80
        links:
            - mongo
            - redis
