---
version: '2.2'
services:

    redis:
        restart: always
        image: "${RC_REDIS_IMAGE}"
        volumes:
            - "${RC_REDIS_DATA_PATH}:/data"
        container_name: redis
        expose:
            - 6379

    sharelatex:
      depends_on:
        redis:
          condition: service_started
      links:
        - redis
